"""
Strategy Document — MongoDB / Beanie

Content plans and growth strategies generated by the AI strategy engine.
"""

from app.utils.datetime_utils import utc_now
from datetime import datetime
from typing import List, Optional

from beanie import Document, Indexed
from pymongo import IndexModel, ASCENDING
from pydantic import Field


class StrategyPlan(Document):
    """A content plan or growth strategy."""

    user_id: Indexed(str)  # type: ignore[valid-type]
    project_id: Optional[str] = None  # ref → projects (nullable for global strategies)

    type: str = "content_plan"  # content_plan | growth_strategy | series
    title: str = ""
    focus_niche: str = ""

    # The full plan payload — typically a list of series items
    content: dict = Field(default_factory=dict)

    # Legacy convenience field — maps to content.series_plan
    series_plan: List[dict] = Field(default_factory=list)

    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)

    class Settings:
        name = "strategies"
        use_state_management = True
        indexes = [
            IndexModel([("user_id", ASCENDING)]),
            IndexModel([("project_id", ASCENDING)]),
            IndexModel([("type", ASCENDING)]),
        ]
