import { useState, useEffect } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { useProjectStore } from '../store/projectStore'
import { ArrowLeft, Plus, History, Play, Trash2 } from 'lucide-react'
import toast from 'react-hot-toast'

export default function Series() {
    const { id } = useParams<{ id: string }>()
    const navigate = useNavigate()
    const { projects, currentProject, fetchProject, createProject, deleteProject } = useProjectStore()

    const [isCreating, setIsCreating] = useState(false)
    const [title, setTitle] = useState('')

    useEffect(() => {
        if (id) {
            fetchProject(id).catch(() => {
                toast.error('Failed to load series')
                navigate('/dashboard')
            })
        }
    }, [id])

    // Find all projects that designate this series as their parent
    const childVideos = projects.filter(p => p.parent_project_id === id)

    const handleCreateChildVideo = async () => {
        if (!title.trim() || !id || !currentProject) return

        setIsCreating(true)
        try {
            // A child video belongs to this series
            const project = await createProject(
                title.trim(), 
                currentProject.topic || 'Autogenerated using Series Context', 
                'video'
            )
            // Need to update parent_project_id on the new project
            const { updateProject } = useProjectStore.getState()
            await updateProject(project.id, { parent_project_id: id })
            
            toast.success('Video attached to series')
            navigate(`/project/${project.id}`)
        } catch (error) {
            toast.error('Failed to create video')
        } finally {
            setIsCreating(false)
            setTitle('')
        }
    }

    if (!currentProject || currentProject.project_type !== 'series') {
        return (
            <div className="min-h-screen bg-bg flex items-center justify-center">
                <div className="w-8 h-8 rounded-full border-4 border-accent border-t-transparent animate-spin" />
            </div>
        )
    }

    return (
        <div className="min-h-screen bg-bg pt-20 pb-32">
            <div className="max-w-4xl mx-auto px-6 space-y-12">
                
                {/* Header */}
                <div className="space-y-6">
                    <button onClick={() => navigate('/dashboard')} className="flex items-center gap-2 text-text-secondary hover:text-text-primary transition-colors text-sm font-medium">
                        <ArrowLeft className="w-4 h-4" />
                        Back to Dashboard
                    </button>

                    <div>
                        <div className="flex items-center gap-3 mb-2">
                            <span className="badge-minimal text-accent border-accent/20">SERIES FOLDER</span>
                            {currentProject.requires_continuity && (
                                <span className="badge-minimal text-primary-400 border-primary-500/20">Sequential Continuity Enabled</span>
                            )}
                        </div>
                        <h1 className="text-4xl font-display font-bold text-text-primary mb-3">
                            {currentProject.title}
                        </h1>
                        <p className="text-text-secondary text-lg">
                            {currentProject.topic || 'No description provided.'}
                        </p>
                    </div>
                </div>

                {/* Quick Add Video */}
                <div className="p-6 bg-surface border border-white/5 rounded-2xl">
                    <h2 className="text-sm font-semibold uppercase tracking-widest text-text-secondary mb-4">Add Video to Series</h2>
                    <div className="flex gap-4">
                        <input 
                            value={title}
                            onChange={e => setTitle(e.target.value)}
                            onKeyDown={e => e.key === 'Enter' && handleCreateChildVideo()}
                            placeholder="Example: Episode 1 - The Beginning"
                            className="flex-1 bg-bg border border-white/10 rounded-xl px-4 py-3 focus:outline-none focus:border-primary-500 text-text-primary"
                        />
                        <button 
                            onClick={handleCreateChildVideo}
                            disabled={!title.trim() || isCreating}
                            className="bg-primary-600 hover:bg-primary-500 text-white px-6 py-3 rounded-xl font-medium transition-colors flex items-center gap-2 disabled:opacity-50"
                        >
                            {isCreating ? 'Creating...' : (
                                <>
                                    <Plus className="w-5 h-5" />
                                    Create Video
                                </>
                            )}
                        </button>
                    </div>
                </div>

                {/* Child Videos List */}
                <div className="space-y-6">
                    <h2 className="flex items-center gap-2 text-sm font-semibold uppercase tracking-widest text-text-secondary">
                        <History className="w-4 h-4" />
                        Series Episodes ({childVideos.length})
                    </h2>

                    <div className="grid gap-3">
                        {childVideos.map((video) => (
                            <div 
                                key={video.id}
                                onClick={() => navigate(`/project/${video.id}`)}
                                className="group flex items-center justify-between p-5 bg-surface/50 border border-white/5 rounded-xl hover:bg-elevated hover:border-white/10 transition-all cursor-pointer"
                            >
                                <div className="flex items-center gap-4">
                                    <div className="w-10 h-10 rounded-full bg-accent/10 flex items-center justify-center">
                                        <Play className="w-4 h-4 text-accent translate-x-0.5" />
                                    </div>
                                    <div>
                                        <h3 className="font-medium text-lg text-text-primary group-hover:text-accent transition-colors">
                                            {video.title}
                                        </h3>
                                        <div className="flex items-center gap-3 text-xs text-text-secondary mt-1">
                                            <span className="font-mono uppercase">{video.status}</span>
                                            <span className="w-1 h-1 rounded-full bg-white/50" />
                                            <span>{new Date(video.created_at).toLocaleDateString()}</span>
                                        </div>
                                    </div>
                                </div>
                                <button 
                                    onClick={async (e) => {
                                        e.stopPropagation()
                                        if (confirm('Delete this video from the series?')) {
                                            await deleteProject(video.id)
                                            toast.success('Video deleted')
                                        }
                                    }}
                                    className="p-2 text-text-secondary hover:text-error transition-colors opacity-0 group-hover:opacity-100"
                                >
                                    <Trash2 className="w-5 h-5" />
                                </button>
                            </div>
                        ))}

                        {childVideos.length === 0 && (
                            <div className="p-12 text-center border border-dashed border-white/5 rounded-2xl">
                                <p className="text-text-secondary font-medium">This series is empty.</p>
                                <p className="text-sm text-text-secondary/60 mt-1">Add your first video above to get started.</p>
                            </div>
                        )}
                    </div>
                </div>

            </div>
        </div>
    )
}
